### ISSUE TITLE
🚨 CI Down 👎 

### ISSUE THREAD

**Issue by adriens** [opt-nc/atelier-spring-kafka#9]
cf https://github.com/opt-nc/atelier-spring-kafka/runs/5280285991?check_suite_focus=true

![image](https://user-images.githubusercontent.com/5235127/155039907-c90be9dc-a708-4433-8acc-ec2cf74735c2.png)

**Comment by adriens** [comment]
il me semble que les PRs passent désormais @mbarre

**Comment by mbarre** [comment]
je viens de rajouter le build sur les PR, ca passe pas :(

**Comment by adriens** [comment]
:hankey:

**Comment by mbarre** [comment]
Ca y est, c'est fixé. C'était Junit qui cassait les pieds...

**Comment by adriens** [comment]
AHHHH, YESS !! Tu as eu sa peau 👏
